### ISSUE TITLE
version 0.18 has no script output, just package.json and readme

### ISSUE THREAD

**Issue by patroza** [mmkal/eslint-plugin-codegen#15]

**Comment by fubhy** [comment]
Haha, hi @patroza I just ran into that too :-D

**Comment by patroza** [comment]
> Haha, hi @patroza I just ran into that too :-D

Funky

**Comment by mmkal** [comment]
Oops! Fixed in 0.18.1

[npm](https://www.npmjs.com/package/eslint-plugin-codegen/v/0.18.1?activeTab=code) [github](https://github.com/mmkal/eslint-plugin-codegen/releases/tag/v0.18.1)
