### ISSUE TITLE
Exclude stops working with v0.18.0

### ISSUE THREAD

**Issue by boredland** [mmkal/eslint-plugin-codegen#20]
With earlier versions I had an exclude as such: `[./utils.ts,./*.test.ts]`. After the upgrade, both are included.

**Comment by mmkal** [comment]
I just looked into this and it looks like it's because of a new bug in `glob`: https://github.com/isaacs/node-glob/issues/570.

To workaround for now you can change to `[utils.ts, *.test.ts]`. I will look into an automatic workaround until the upstream issue is fixed.

**Comment by isaacs** [comment]
Specifically, this is an issue with an ignore pattern that starts with `./`. Relative patterns starting with `../` or some other string or pattern work fine.
