### ISSUE TITLE
Support vitest

### ISSUE THREAD

**Issue by ahrjarrett** [mmkal/eslint-plugin-codegen#22]
Hello @mmkal, this library is a gem, I've been using it in my own projects and have put it "into prod" more than once, and have always gotten good feedback from my users, a few of which have started integrating it into their own libraries.

I'd be curious to hear if you have any plans to support [Vitest](https://github.com/vitest-dev/vitest) in the future?

**Comment by mmkal** [comment]
I use it with vitest already! Have you tried it?

**Comment by mmkal** [comment]
Very happy to accept a pull request to either update the docs to declare vitest officially supported, or if there's a specific problem you've had with vitest, let me know.

**Comment by ahrjarrett** [comment]
Ah, yes it does :) I remember trying at one point and thinking it wasn't supported yet. Now that I'm looking at the docs, you do actually specify that, probably was just user error on my part.

Thank you!
